### ISSUE TITLE
O sistema está salvando com null o endereço

### ISSUE THREAD

**Issue by ellensilva** [vtex/front.shipping-data#14]
usuário já indentificado
basedevmkp.vtexcommercebeta.com.br/checkout/cart/add?sku=2390113&qty=1&seller=1&redirect=true&sc=1
informar cep fora da lista do usuário no carrinho
Ir para a tela de endereço
Será apresentado a tela com o cep preenchido
Clicar em voltar para a lista de endereço
Verificar que na lista será apresentado o cep preenchido no carrinho com os dados null

**Comment by brenoc** [comment]
Erro já não acontece mais.
