### ISSUE TITLE
Remover "a partir de" caso todos os preços da entrega agendada sejam o mesmo

### ISSUE THREAD

**Issue by firstdoit** [vtex/front.shipping-data#16]

**Comment by vtexcrmgithub** [comment]
[Link do CRM.](http://vtexcrm.vtexcrm.com.br/home/index/ML-1000138)
[Wiki da Integração.](https://github.com/vtex/crm/wiki/Integra%C3%A7%C3%A3o-CRM-x-GitHub)

**Comment by vtexcrmgithub** [comment]
[Link do CRM.](http://vtexcrm.vtexcrm.com.br/home/index/ML-1000137)
[Wiki da Integração.](https://github.com/vtex/crm/wiki/Integra%C3%A7%C3%A3o-CRM-x-GitHub)

**Comment by brenoc** [comment]
pubilshedbeta
