### ISSUE TITLE
Frame de Entrega não acompanha mudanças no carrinho

### ISSUE THREAD

**Issue by gustavo-almeida** [vtex/front.shipping-data#17]
**Também ocorre em stable**

Condições:
1. Possuir um item que, aumentando a quantidade, seja entregue por duas Docas diferentes. (De preferência com Docas que possuam prazos diferentes.)

Passos:
1. Avançar com o item até o pagamento;
2. Voltar para o carrinho;
3. Aumentar a quantidade de itens até que a segunda doca seja usada, ou seja, de forma que o valor do frete e/ou prazo sejam alterados.
4. Avançar até o pagamento.

Frame de Entrega continua com informações anteriores aos novos dados de frete e valor:
![capturar](https://cloud.githubusercontent.com/assets/5751468/6021177/ed3c930c-ab9a-11e4-9564-0ceff00ffee0.PNG)

**Comment by brenoc** [comment]
publishedbeta

**Comment by brenoc** [comment]
teste

**Comment by brenoc** [comment]
teste

**Comment by ygorops** [comment]
Integrando Issue com CRM.

**Comment by vtexcrmgithub** [comment]
[Link do CRM.](http://vtex.vtexcrm.com.br/home/index/PI-649)
[Wiki da Integração.](https://github.com/vtex/crm/wiki/Integra%C3%A7%C3%A3o-CRM-x-GitHub)

**Comment by brenoc** [comment]
publishedbeta

**Comment by vtexcrmgithub** [comment]
Publicação em Beta via comando do Wiki.

**Comment by brenoc** [comment]
publishedstable

**Comment by vtexcrmgithub** [comment]
Publicação em Produção via comando do Wiki.
