### ISSUE TITLE
[CHILE] Nome  da Comuna escrito de forma incorreta

### ISSUE THREAD

**Issue by vtexcrmgithub** [vtex/front.shipping-data#18]
É necessário, nas Lojas do Chile, alterar em Comuna o nome "Coihaique" para "Coyhaique", ou seja, alterando a primeira letra "i" por "y".

Para visualizar o grupo de Comunas onde esta encontra-se, é necessário primeiramente selecionar a Região "XI Región"

Segue imagem em anexo.

**Comment by vtexcrmgithub** [comment]
[Link do CRM.](http://vtex.vtexcrm.com.br/home/index/PC-1162)
[Wiki da Integração.](https://github.com/vtex/crm/wiki/Integra%C3%A7%C3%A3o-CRM-x-GitHub)

**Comment by vtexcrmgithub** [comment]
#### Issue Movida para este projeto
Usuário que moveu essa Issue: @brenoc

**Comment by brenoc** [comment]
publishedbeta

**Comment by brenoc** [comment]
teste

**Comment by brenoc** [comment]
publishedbeta

**Comment by ygorops** [comment]
publishedbeta

**Comment by vtexcrmgithub** [comment]
Publicação em Beta via comando do Wiki.

**Comment by brenoc** [comment]
publishedstable

**Comment by vtexcrmgithub** [comment]
Publicação em Produção via comando do Wiki.
