### ISSUE TITLE
Ampliar Zipcodes en Perú y completar el País

### ISSUE THREAD

**Issue by vtexcrmgithub** [vtex/front.shipping-data#19]
Necesitamos ampliar los zipcodes configurados actualmente a todo Perú. Hoy solo esta configurado Lima.

Adjunto los códigos UBIGEO completos. Estos deben ser agregados a los que hoy se encuentran configurados. Los UBIGEO son los zipcodes utilizados en Perú.

La planilla adjunta contiene las siguientes columnas: 
CÓDIGO UBIGEO / DEPARTAMENTO / PROVINCIA / DISTRITO

IMPORTANTE:
Departamento: LIMA, debe estar primero en la lista.
Provincia: LIMA, debe estar primero en la lista.
Distrito: LIMA, debe estar primero en la lista.

Por favor, avanzar con la carga. Gracias!!

Arquivo: http://goo.gl/NFy80B

**Comment by vtexcrmgithub** [comment]
[Link do CRM.](http://vtex.vtexcrm.com.br/home/index/PC-1192)
[Wiki da Integração.](https://github.com/vtex/crm/wiki/Integra%C3%A7%C3%A3o-CRM-x-GitHub)

**Comment by brenoc** [comment]
publishedbeta

**Comment by vtexcrmgithub** [comment]
Publicação em Beta via comando do Wiki.

**Comment by vtexcrmgithub** [comment]
Fiz o teste na loja http://www.tiendanettalco.pe/ e a ordenação não está conforme definido.

CASO 1: A opção Lima não aparece em primeiro na combo Departamento.

CASO 2: A Províncias e Distritos não estão ordenados alfabeticamente. Nessas combos, Lima aparece corretamente em primeiro. Ver imagem em anexo.

![Ordenação](http://melissa-clouddrive.s3.amazonaws.com/erros/ordenacao-provincia-distrito.gif)

Grato(a),
@melissaotero

**Comment by brenoc** [comment]
publishedbeta

**Comment by vtexcrmgithub** [comment]
Publicação em Beta via comando do Wiki.

**Comment by vtexcrmgithub** [comment]
Teste OK!

Lima agora aparece em primeiro nas 3 combos, conforme solicitado e as outras localidades estão ordenadas alfabeticamente.

Grato(a),
@melissaotero

**Comment by brenoc** [comment]
publishedstable

**Comment by vtexcrmgithub** [comment]
Publicação em Produção via comando do Wiki.
