### ISSUE TITLE
Erro ao cancelar alterações e voltar para a lista de endereços

### ISSUE THREAD

**Issue by brenoc** [vtex/front.shipping-data#20]
Ao clicar no botão o erro abaixo aparece:

```javascript
 Uncaught event requestSLA inappropriate in current state searchstate-machine.js:76 
```

**Comment by vtexcrmgithub** [comment]
[Link do CRM.](http://vtex.vtexcrm.com.br/home/index/PI-680)
[Wiki da Integração.](https://github.com/vtex/crm/wiki/Integra%C3%A7%C3%A3o-CRM-x-GitHub)

**Comment by brenoc** [comment]
publishedbeta

**Comment by vtexcrmgithub** [comment]
Publicação em Beta via comando do Wiki.

**Comment by vtexcrmgithub** [comment]
Teste OK!

Grato(a),
@melissaotero

**Comment by brenoc** [comment]
publishedstable

**Comment by vtexcrmgithub** [comment]
Publicação em Produção via comando do Wiki.
