### ISSUE TITLE
Erro ao tentar entregar para um novo endereço quando comprando para lista

### ISSUE THREAD

**Issue by brenoc** [vtex/front.shipping-data#21]
Vídeo mostrando o erro:
http://chilp.it/f57bd89

**Comment by brenoc** [comment]
Fix cd4f3bc7c0c0b6c71973fd52562db8c91da799e6

**Comment by vtexcrmgithub** [comment]
[Link do CRM.](http://vtexcrm.vtexcrm.com.br/home/index/PI-1000061)
[Wiki da Integração.](https://github.com/vtex/crm/wiki/Integra%C3%A7%C3%A3o-CRM-x-GitHub)

**Comment by brenoc** [comment]
publishedstable

**Comment by vtexcrmgithub** [comment]
Publicação em Produção via comando do Wiki.
